services:
  api:
    build:
      target: dev
    environment:
      CORS_ALLOW_ORIGINS: '["http://ui:5173"]'
    volumes:
      - ./api/app:/api
  db:
    environment:
      EDGEDB_SERVER_ADMIN_UI: enabled
    volumes:
      - ./db:/db
  ui:
    build:
      target: dev
    ports:
      - 5173:5173
    volumes:
      - ./ui/src:/ui/src
