@_help:
    just --list

# Run the server.
@run:
    env EDGEDB_DSN="$( \
        edgedb instance credentials \
            --insecure-dsn \
            --instance mishpocha_db \
        )?tls_security=insecure" \
    cargo run
